// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Telefon açıklaması.",
                            ImageUrl = "1.png",
                            IsActive = true,
                            ProductName = "IPhone 16 Pro",
                            ProductPrice = 87999m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Telefon açıklaması2.",
                            ImageUrl = "2.png",
                            IsActive = true,
                            ProductName = "IPhone 11 Pro Max",
                            ProductPrice = 41000m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Telefon açıklaması3.",
                            ImageUrl = "3.png",
                            IsActive = true,
                            ProductName = "Poco",
                            ProductPrice = 21000m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Telefon açıklaması4.",
                            ImageUrl = "4.png",
                            IsActive = true,
                            ProductName = "Samsung Galaxy S24",
                            ProductPrice = 45000m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Telefon açıklaması5.",
                            ImageUrl = "5.png",
                            IsActive = true,
                            ProductName = "IPhone 15 Pro",
                            ProductPrice = 99999m,
                            Stock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
